<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net462;net48;net8.0;net10.0</TargetFrameworks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>1.1.1</Version>
		<Authors>Joel Christner</Authors>
		<Company>Joel Christner</Company>
		<Copyright>(c)2026 Joel Christner</Copyright>
		<PackageProjectUrl>https://github.com/jchristn/regexmatcher</PackageProjectUrl>
		<RepositoryUrl>https://github.com/jchristn/regexmatcher</RepositoryUrl>
		<RepositoryType>Github</RepositoryType>
		<PackageTags>regex match regular expression</PackageTags>
		<PackageReleaseNotes>Test dependency updates (Touchstone 0.2.0, NUnit 5.0.0, Microsoft.NET.Test.Sdk 18.10.1); no library or API changes</PackageReleaseNotes>
		<Description>Regular expression matching library.</Description>
		<ApplicationIcon>icon.ico</ApplicationIcon>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>RegexMatcher.xml</DocumentationFile>
		<Title>RegexMatcher</Title>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="icon.ico" />
		<Content Include="LICENSE.md">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\..\assets\icon.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\..\LICENSE.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<None Update="LICENSE.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="RegexMatcher.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
